apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: opentelemetry-demo-productcatalogservice
spec:
  hosts:
    - opentelemetry-demo-productcatalogservice
  http:
    - route:
      - destination:
          host: opentelemetry-demo-productcatalogservice
      timeout: 2s